# Generated by Django 3.2.9 on 2021-11-19 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_cats_cat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
